# Generated by Django 4.2.6 on 2023-10-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websitescrapper_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='links',
            name='stringname',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
